CREATE TABLE IF NOT EXISTS Item
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    brandId      VARCHAR(255) NOT NULL,
    brandName    VARCHAR(255) NOT NULL,
    categoryCode VARCHAR(255) NOT NULL,
    categoryName VARCHAR(255) NOT NULL,
    price        INT          NOT NULL,
    createdId    VARCHAR(255) NOT NULL,
    createdAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedId    VARCHAR(255),
    updatedAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Category
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    code      VARCHAR(255) NOT NULL UNIQUE,
    name      VARCHAR(255) NOT NULL,
    createdId VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedId VARCHAR(255),
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Brand
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    createdId VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedId VARCHAR(255),
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);